apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/quay-operator.openshift-operators: ""
  name: quay-operator
  namespace: openshift-operators
spec:
  channel: stable-3.10
  installPlanApproval: Automatic
  name: quay-operator
  source: redhat-operators-snapshot-pipelines
  sourceNamespace: openshift-operators
  startingCSV: quay-operator.v3.10.4
